name: GitHub-Profile-3D-Contrib
on:
  schedule:
      - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name rhMichael
          git config user.email michaelrh471@outlook.com
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/rhMichael/rhMichael.git
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
